### PR TITLE
Add a Semigroup instance for SrcLoc

### PR DESCRIPTION
**Pull request by ckoparkar**
In GHC 8.4 `Semigroup` is a superclass of `Monoid`.

### CODE REVIEW

**Comment by ckoparkar** [comment]
Hey @mainland. Have you had a chance to review this ?

**Comment by ckoparkar** [comment]
@mainland Ping.

**Comment by truls** [comment]
I would really like to see this merged as well

**Comment by ckoparkar** [comment]
Thanks!

**Pull request merged**
